sudo: false
services:
  - docker

cache:
    directories:
     - $HOME/.cache

language: cpp

env:
    matrix:
      - OS=el DIST=6
      - OS=el DIST=7
      - OS=fedora DIST=25
      - OS=opensuse DIST=42.2
      - OS=ubuntu DIST=trusty
      - OS=ubuntu DIST=xenial
      - OS=ubuntu DIST=xenial ARCH=i386

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

script:
  - cmake . && make -j3 VERBOSE=1

